# Julian A. Magrata
print("========================================")
print("\t\tEXPENSIVE TRACKER")
print("\tKnow where your money goes.")
print("=" * 40)
print("\nWelcome! This is your personal expense tracker.\n")
print("Main menu")
print("\t1) Add an expenses\t(coming soon)")
print("\t2) View all expenses\t(coming soon)")
print("\t3) Show total spent\t(coming soon)")
print("\t4) Exit\t\t(coming soon)")
print("\n--------------------------------------")
print("Made by: Julian A. Magrata | Installment 1")
print("========================================")